@SanityTest
Feature: Repos Per programming language page body
  Scenario: Validate all features of repos per programming language body
    Given User is on the "https://webuildsg.github.io/data/dataset/repos-per-programming-language/" page to validate all the features of it
    Then user finds the "repositories per programming languages" header text
    And the header text is in hex color code "228db7"
    And the header text font is in "Roboto Slab, serif"
    Then user finds the count of total radio buttons in the page to be "20"
    Then try clicking on the following radio buttons and check the new urls as mentioned
    |radioButtons|newUrls|
    |C|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#c|
    |C++|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#c++|
    |Clojure|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#clojure|
    |CoffeeScript|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#coffeescript|
    |CSS|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#css|
    |Go|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#go|
    |Haskell|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#haskell|
    |HTML|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#html|
    |Java|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#java|
    |JavaScript|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#javascript|
    |Julia|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#julia|
    |Objective-C|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#objective-c|
    |PHP|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#php|
    |Python|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#python|
    #|R|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#r|
    |Ruby|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#ruby|
    |Rust|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#rust|
    |Shell|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#shell|
    |Swift|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#swift|
    |Tex|https://webuildsg.github.io/data/dataset/repos-per-programming-language/#tex|
    Then test if the user clicks on the "C" radio button the following url and stats are displayed
    |linkTextOfUrl|url|startCnt|
    |pili-librtmp|https://github.com/pili-engineering/pili-librtmp|75|
    |novena-linux|https://github.com/xobs/novena-linux|81|
    |pathgrind|https://github.com/codelion/pathgrind|69|
    |grainuum|https://github.com/xobs/grainuum|64|
    |mod_cloudflare|https://github.com/cloudflare/mod_cloudflare|118|
    |textfairy|https://github.com/renard314/textfairy|503|
    |XRulez|https://github.com/mwrlabs/XRulez|60|
    Then test if the user clicks on the "C++" radio button the following url and stats are displayed
    |linkTextOfUrl|url|startCnt|
    |CurvatureFilter|https://github.com/YuanhaoGong/CurvatureFilter|103|
		|graphmap|https://github.com/isovic/graphmap|92|
		|Play-with-Algorithms|https://github.com/liuyubobobo/Play-with-Algorithms|170|
		|ACM_Notebook_new|https://github.com/ngthanhtrung23/ACM_Notebook_new|118|
		|cashew|https://github.com/billhsu/cashew|66|
		|jUART|https://github.com/billhsu/jUART|118|
		|uSpeech|https://github.com/arjo129/uSpeech|312|
		|GMS-Feature-Matcher|https://github.com/JiawangBian/GMS-Feature-Matcher|317|
		|websocket|https://github.com/OKCoin/websocket|91|
		|qtum|https://github.com/qtumproject/qtum|92|
		|phimpme-android|https://github.com/fossasia/phimpme-android|107|
		|FlowNet|https://github.com/liruoteng/FlowNet|61|
		|racon|https://github.com/isovic/racon|62|
		|thundersvm|https://github.com/zeyiwen/thundersvm|614|
		|mmLoader|https://github.com/tishion/mmLoader|78|
		|q_Wind|https://github.com/FlyingOE/q_Wind|50|
		|LittleArduinoProjects|https://github.com/tardate/LittleArduinoProjects|134|
    Then test if the user clicks on the "Clojure" radio button the following url and stats are displayed
    |linkTextOfUrl|url|startCnt|
		|status-react|https://github.com/status-im/status-react|416|
		|core.matrix|https://github.com/mikera/core.matrix|546|
		|instaparse-cljs|https://github.com/lbradstreet/instaparse-cljs|86|
		|vectorz-clj|https://github.com/mikera/vectorz-clj|171|
		|clojure-utils|https://github.com/mikera/clojure-utils|93|
		|clisk|https://github.com/mikera/clisk|237|
    Then test if the user clicks on the "CoffeeScript" radio button the following url and stats are displayed
    |linkTextOfUrl|url|startCnt|
		|www.submarinecablemap.com|https://github.com/telegeography/www.submarinecablemap.com|364|
		|md-writer|https://github.com/zhuochun/md-writer|247|
		|twigjs|https://github.com/fadrizul/twigjs|60|
    Then test if the user clicks on the "CSS" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|pokemon-font|https://github.com/Superpencil/pokemon-font|71|
		|2017.fossasia.org|https://github.com/fossasia/2017.fossasia.org|117|
		|repokemon|https://github.com/cheeaun/repokemon|238|
		|typi|https://github.com/zellwk/typi|699|
		|fossasia.org|https://github.com/fossasia/fossasia.org|342|
		|markdown-css-themes|https://github.com/jasonm23/markdown-css-themes|602|
		|tale|https://github.com/chesterhow/tale|152|
		|adaptive-placeholders|https://github.com/zellwk/adaptive-placeholders|108|
		|hexo-theme-magnetic|https://github.com/klugjo/hexo-theme-magnetic|63|
		|gci17.fossasia.org|https://github.com/fossasia/gci17.fossasia.org|282|
		|events.fossasia.org|https://github.com/fossasia/events.fossasia.org|105|
		|2018.fossasia.org|https://github.com/fossasia/2018.fossasia.org|251|
		|2015.fossasia.org|https://github.com/fossasia/2015.fossasia.org|201|
		|2016.fossasia.org|https://github.com/fossasia/2016.fossasia.org|264|
		Then test if the user clicks on the "Go" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|cloudflare-go|https://github.com/cloudflare/cloudflare-go|92|
		|cfssl|https://github.com/cloudflare/cfssl|2255|
		|go|https://github.com/cloudflare/go|162|
		|tls-tris|https://github.com/cloudflare/tls-tris|100|
		|ccache|https://github.com/karlseguin/ccache|83|
		|canopus|https://github.com/zubairhamed/canopus|69|
		|gokeyless|https://github.com/cloudflare/gokeyless|111|
		|cfssl_trust|https://github.com/cloudflare/cfssl_trust|61|
		|unsee|https://github.com/cloudflare/unsee|137|
		|gopl-solutions|https://github.com/vinceyuan/gopl-solutions|51|
		|slumber|https://github.com/sogko/slumber|349|
		|golibs|https://github.com/cloudflare/golibs|248|
		|redoctober|https://github.com/cloudflare/redoctober|1037|
		|dynacasbin|https://github.com/HOOQTV/dynacasbin|77|
		|machinery|https://github.com/RichardKnop/machinery|1944|
		Then test if the user clicks on the "Haskell" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|hpack|https://github.com/sol/hpack|238|
		|doctest|https://github.com/sol/doctest|225|
		|DeepDarkFantasy|https://github.com/ThoughtWorksInc/DeepDarkFantasy|353|
		|reserve|https://github.com/sol/reserve|55|
		|json-autotype|https://github.com/mgajda/json-autotype|51|
		|markdown-unlit|https://github.com/sol/markdown-unlit|55|
		Then test if the user clicks on the "HTML" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|FEND_Note|https://github.com/li-xinyang/FEND_Note|1072|
		|app-datepicker|https://github.com/motss/app-datepicker|78|
		|hexo-theme-alpha-dust|https://github.com/klugjo/hexo-theme-alpha-dust|70|
		|miniCRAN|https://github.com/RevolutionAnalytics/miniCRAN|59|
		|learnyouahaskell-zh|https://github.com/MnO2/learnyouahaskell-zh|269|
		|hexo-theme-clean-blog|https://github.com/klugjo/hexo-theme-clean-blog|147|
		|life|https://github.com/cheeaun/life|2309|
		|pslab.fossasia.org|https://github.com/fossasia/pslab.fossasia.org|79|
		|multi-step-modal|https://github.com/ngzhian/multi-step-modal|74|
		|traprange|https://github.com/thoqbk/traprange|88|
		|2017.fossasia.org|https://github.com/fossasia/2017.fossasia.org|214|
		|2012.fossasia.org|https://github.com/fossasia/2012.fossasia.org|235|
		|2014.fossasia.org|https://github.com/fossasia/2014.fossasia.org|126|
		Then test if the user clicks on the "Java" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|teammates|https://github.com/TEAMMATES/teammates|518|
		|materialistic|https://github.com/hidroh/materialistic|1135|
		|susi_android|https://github.com/fossasia/susi_android|202|
		|qiscus-sdk-android|https://github.com/qiscus/qiscus-sdk-android|120|
		|open-event-android|https://github.com/fossasia/open-event-android|712|
		|SquareCamera|https://github.com/boxme/SquareCamera|531|
		|RootManager|https://github.com/Chrisplus/RootManager|101|
		|PLDroidPlayer|https://github.com/pili-engineering/PLDroidPlayer|3016|
		|ScrollablePanel|https://github.com/PoePoeMyintSwe/ScrollablePanel|60|
		|pili-sdk-java|https://github.com/pili-engineering/pili-sdk-java|83|
		|FaceRecognition|https://github.com/wihoho/FaceRecognition|97|
		|phimpme-android|https://github.com/fossasia/phimpme-android|556|
		|Android-WVersionManager|https://github.com/winsontan520/Android-WVersionManager|138|
		|docs-to-pdf-converter|https://github.com/yeokm1/docs-to-pdf-converter|107|
		|TextDrawable|https://github.com/amulyakhare/TextDrawable|2514|
		|susi_server|https://github.com/fossasia/susi_server|544|
		|PLDroidMediaStreaming|https://github.com/pili-engineering/PLDroidMediaStreaming|986|
		|app-icon|https://github.com/dwmkerr/app-icon|180|
		|Android-WScratchView|https://github.com/winsontan520/Android-WScratchView|74|
		|kiss|https://github.com/mikera/kiss|76|
		|icefig|https://github.com/WorksApplications/icefig|142|
		|mintube|https://github.com/imshyam/mintube|205|
		|TechInterview|https://github.com/SuyashLakhotia/TechInterview|108|
		|PLDroidShortVideo|https://github.com/pili-engineering/PLDroidShortVideo|715|
		|vectorz|https://github.com/mikera/vectorz|131|
		|Sudachi|https://github.com/WorksApplications/Sudachi|188|
		|InMemoryJavaCompiler|https://github.com/trung/InMemoryJavaCompiler|73|
		|pslab-android|https://github.com/fossasia/pslab-android|193|
		|jcgroup|https://github.com/haosdent/jcgroup|124|
		|financisto2|https://github.com/dsolonenko/financisto2|121|
		Then test if the user clicks on the "JavaScript" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|metalsmith-react-templates|https://github.com/yeojz/metalsmith-react-templates|72|
		|getaroom|https://github.com/Temasys/getaroom|145|
		|create-react-app-now|https://github.com/xkawi/create-react-app-now|127|
		|SkylinkJS|https://github.com/Temasys/SkylinkJS|215|
		|npm-programmatic|https://github.com/Manak/npm-programmatic|66|
		|backgrid|https://github.com/cloudflare/backgrid|2010|
		|html2canvas|https://github.com/niklasvh/html2canvas|10592|
		|react-universal-saga|https://github.com/xkawi/react-universal-saga|124|
		|Restler|https://github.com/Luracast/Restler|1226|
		|react-native-flip-card|https://github.com/moschan/react-native-flip-card|131|
		|django-reactjs-boilerplate|https://github.com/mbrochh/django-reactjs-boilerplate|408|
		|gwp|https://github.com/sausheong/gwp|203|
		|nativefier|https://github.com/jiahaog/nativefier|13345|
		|vue-google-signin-button|https://github.com/phanan/vue-google-signin-button|73|
		|angular-multi-select|https://github.com/isteven/angular-multi-select|1042|
		|open-event-webapp|https://github.com/fossasia/open-event-webapp|609|
		|react-native-simple-radio-button|https://github.com/moschan/react-native-simple-radio-button|170|
		|npm-run|https://github.com/timoxley/npm-run|143|
		|angularjs-pdf|https://github.com/sayanee/angularjs-pdf|450|
		|cf-ui|https://github.com/cloudflare/cf-ui|1255|
		|AdapterJS|https://github.com/Temasys/AdapterJS|300|
		|space-radar|https://github.com/zz85/space-radar|651|
		|node-hnapi|https://github.com/cheeaun/node-hnapi|208|
		|react-native-credit-card-input|https://github.com/sbycrosz/react-native-credit-card-input|518|
		|apps.loklak.org|https://github.com/fossasia/apps.loklak.org|57|
		|angular-modal-service|https://github.com/dwmkerr/angular-modal-service|618|
		|2048-as-a-service|https://github.com/Semantics3/2048-as-a-service|128|
		|c4|https://github.com/kenrick95/c4|59|
		|linklocal|https://github.com/timoxley/linklocal|250|
		|react-modal2|https://github.com/cloudflare/react-modal2|220|
		|webuild|https://github.com/webuildsg/webuild|58|
		|react-sidenav|https://github.com/wmira/react-sidenav|151|
		|vue-google-maps|https://github.com/xkjyeah/vue-google-maps|564|
		|angular-spotify|https://github.com/eddiemoore/angular-spotify|205|
		|functional-javascript-workshop|https://github.com/timoxley/functional-javascript-workshop|1590|
		|tappable|https://github.com/cheeaun/tappable|314|
		|nusmods|https://github.com/nusmodifications/nusmods|172|
		|charming|https://github.com/yuanqing/charming|365|
		|guia-de-desenvolvimento-tecnico|https://github.com/ThoughtWorksInc/guia-de-desenvolvimento-tecnico|86|
		|connected-react-router|https://github.com/supasate/connected-react-router|225|
		|react-native-pull-to-refresh|https://github.com/moschan/react-native-pull-to-refresh|88|
		|keycode|https://github.com/timoxley/keycode|274|
		|blitz-cli|https://github.com/sonnylazuardi/blitz-cli|57|
		|chat.susi.ai|https://github.com/fossasia/chat.susi.ai|342|
		|doca|https://github.com/cloudflare/doca|95|
		|chromelens|https://github.com/chromelens/chromelens|312|
		|frapid|https://github.com/frapid/frapid|61|
		|front-end-guide|https://github.com/grab/front-end-guide|9261|
		|tech-interview-handbook|https://github.com/yangshun/tech-interview-handbook|13984|
		|awesome-spinners|https://github.com/yangshun/awesome-spinners|84|
		|koa-react-isomorphic|https://github.com/hung-phan/koa-react-isomorphic|130|
		|gulp-starter-csstricks|https://github.com/zellwk/gulp-starter-csstricks|243|
		|combo-select|https://github.com/PebbleRoad/combo-select|68|
		|attache-rails|https://github.com/choonkeat/attache-rails|52|
		|renovate|https://github.com/singapore/renovate|186|
		|doxity|https://github.com/DigixGlobal/doxity|51|
		|open-event-frontend|https://github.com/fossasia/open-event-frontend|104|
		|react-native-credit-card|https://github.com/sonnylazuardi/react-native-credit-card|187|
		|puppetron|https://github.com/cheeaun/puppetron|59|
		|zoom-vanilla.js|https://github.com/spinningarrow/zoom-vanilla.js|70|
		|otplib|https://github.com/yeojz/otplib|72|
		|musicAPI|https://github.com/LIU9293/musicAPI|219|
		|elasticsearch-streams|https://github.com/hmalphettes/elasticsearch-streams|54|
		|punch|https://github.com/laktek/punch|1201|
		|lago|https://github.com/yangshun/lago|63|
		|pili-sdk-nodejs|https://github.com/pili-engineering/pili-sdk-nodejs|52|
		|react-doc-meta|https://github.com/geekyme/react-doc-meta|59|
		|cezerin|https://github.com/cezerin/cezerin|177|
		|columnify|https://github.com/timoxley/columnify|261|
		|react-native-nike-running|https://github.com/sonnylazuardi/react-native-nike-running|488|
		|nk-missile-tests|https://github.com/nagix/nk-missile-tests|54|
		|publiccode.asia|https://github.com/fossasia/publiccode.asia|63|
		|load-google-maps-api|https://github.com/yuanqing/load-google-maps-api|52|
		|TagUI|https://github.com/tebelorg/TagUI|2593|
		|kopi.js|https://github.com/KopiJS/kopi.js|110|
		|BossBot.io|https://github.com/Singapore-Tech-Entrepreneurs/BossBot.io|67|
		|tc|https://github.com/mccxiv/tc|77|
		|rn-nodeify|https://github.com/tradle/rn-nodeify|196|
		|sylphy|https://github.com/pyraxo/sylphy|58|
		|redisdown|https://github.com/hmalphettes/redisdown|66|
		|react-native-crypto|https://github.com/tradle/react-native-crypto|120|
		|labyrinth|https://github.com/fossasia/labyrinth|206|
		|webrtc-video-chat|https://github.com/piratefsh/webrtc-video-chat|60|
		|es2017-lambda-boilerplate|https://github.com/irvinlim/es2017-lambda-boilerplate|65|
    Then test if the user clicks on the "Julia" radio button the following url and stats are displayed
	  |linkTextOfUrl|url|startCnt|
    |DecisionTree.jl|https://github.com/bensadeghi/DecisionTree.jl|99|
    Then test if the user clicks on the "Objective-C" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
    |FastImageCache|https://github.com/path/FastImageCache|7513|
		|ScalePicker|https://github.com/kronik/ScalePicker|125|
		|SPPatternLock|https://github.com/freesuraj/SPPatternLock|145|
		|PLMediaStreamingKit|https://github.com/pili-engineering/PLMediaStreamingKit|320|
		|FRHyperLabel|https://github.com/null09264/FRHyperLabel|117|
		|SPAnalogClock|https://github.com/freesuraj/SPAnalogClock|98|
		|STPopup|https://github.com/kevin0571/STPopup|2005|
		|PLPlayerKit|https://github.com/pili-engineering/PLPlayerKit|1202|
		|POP-MCAnimate|https://github.com/matthewcheok/POP-MCAnimate|929|
		|PaperFoldMenuController|https://github.com/honcheng/PaperFoldMenuController|460|
		|Volkswagen-Xcode|https://github.com/cezheng/Volkswagen-Xcode|106|
		|Flycut|https://github.com/TermiT/Flycut|808|
		|GTScrollNavigationBar|https://github.com/luugiathuy/GTScrollNavigationBar|539|
		|LXReorderableCollectionViewFlowLayout|https://github.com/lxcid/LXReorderableCollectionViewFlowLayout|1670|
		|RTLabel|https://github.com/honcheng/RTLabel|1356|
		|MKStoreKit|https://github.com/MugunthKumar/MKStoreKit|2076|
		|STPopupPreview|https://github.com/kevin0571/STPopupPreview|167|
		|Firebase|https://github.com/soheilbm/Firebase|65|
		|JJPluralForm|https://github.com/junjie/JJPluralForm|53|
		|STXDynamicTableView|https://github.com/2359media/STXDynamicTableView|357|
		|PLShortVideoKit|https://github.com/pili-engineering/PLShortVideoKit|83|
		|react-native-udp|https://github.com/tradle/react-native-udp|112|
		Then test if the user clicks on the "PHP" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|eloquence|https://github.com/jarektkaczyk/eloquence|665|
		|inoERP|https://github.com/inoerp/inoERP|249|
		|Cloudflare-CPanel|https://github.com/cloudflare/Cloudflare-CPanel|76|
		|koel|https://github.com/phanan/koel|8318|
		|bones-for-genesis-2-0|https://github.com/cdukes/bones-for-genesis-2-0|168|
		|kupo|https://github.com/phanan/kupo|293|
		|revisionable|https://github.com/jarektkaczyk/revisionable|226|
		|wp-sweep|https://github.com/lesterchan/wp-sweep|85|
		|wp-postratings|https://github.com/lesterchan/wp-postratings|74|
		|php-queue|https://github.com/CoderKungfu/php-queue|577|
		|wp-postviews|https://github.com/lesterchan/wp-postviews|80|
		|laravel-dynamodb|https://github.com/baopham/laravel-dynamodb|84|
		|StateMachineBundle|https://github.com/winzou/StateMachineBundle|166|
		|wp-polls|https://github.com/lesterchan/wp-polls|56|
		|wp-pagenavi|https://github.com/lesterchan/wp-pagenavi|87|
		|state-machine|https://github.com/winzou/state-machine|153|
		Then test if the user clicks on the "Python" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|open-event-orga-server|https://github.com/fossasia/open-event-orga-server|459|
		|terminal_markdown_viewer|https://github.com/axiros/terminal_markdown_viewer|475|
		|lizard|https://github.com/terryyin/lizard|404|
		|needle|https://github.com/mwrlabs/needle|664|
		|shadowsocks-py-mu|https://github.com/fsgmhoward/shadowsocks-py-mu|182|
		|thesaurus_query.vim|https://github.com/Ron89/thesaurus_query.vim|74|
		|pymessenger|https://github.com/davidchua/pymessenger|312|
		|django-libs|https://github.com/bitlabstudio/django-libs|72|
		|jira-cli|https://github.com/alisaifee/jira-cli|88|
		|CubeMX2Makefile|https://github.com/baoshi/CubeMX2Makefile|120|
		|drozer|https://github.com/mwrlabs/drozer|1243|
		|flask-limiter|https://github.com/alisaifee/flask-limiter|278|
		|win_driver_plugin|https://github.com/mwrlabs/win_driver_plugin|140|
		|doublepulsar-detection-script|https://github.com/countercept/doublepulsar-detection-script|785|
		|face_morpher|https://github.com/alyssaq/face_morpher|299|
		|decaptcha|https://github.com/Yaoshicn/decaptcha|76|
		|django-review|https://github.com/bitlabstudio/django-review|55|
		|DataMiningCompetitionFirstPrize|https://github.com/lzddzh/DataMiningCompetitionFirstPrize|54|
		|meilix|https://github.com/fossasia/meilix|103|
		|cloudflare-blog|https://github.com/cloudflare/cloudflare-blog|74|
		|volatility-trading|https://github.com/jasonstrimpel/volatility-trading|93|
		|python-email-crawler|https://github.com/samwize/python-email-crawler|126|
		|DPNs|https://github.com/cypw/DPNs|256|
		|drozer-modules|https://github.com/mwrlabs/drozer-modules|65|
		|open-event|https://github.com/fossasia/open-event|89|
		|python-cloudflare|https://github.com/cloudflare/python-cloudflare|72|
		|ansible-ssh-config|https://github.com/gaqzi/ansible-ssh-config|78|
		|google-translate-python|https://github.com/terryyin/google-translate-python|186|
		|query-server|https://github.com/fossasia/query-server|235|
		|sec-edgar|https://github.com/rahulrrixe/sec-edgar|102|
		|badgeyay|https://github.com/fossasia/badgeyay|303|
		|ZipBomb|https://github.com/abdulfatir/ZipBomb|160|
		|mythril|https://github.com/b-mueller/mythril|202|
		|django-influxdb-metrics|https://github.com/bitlabstudio/django-influxdb-metrics|56|
		|uSpeech|https://github.com/arjo129/uSpeech|345|
		|OS_FrontendMaster-dl|https://github.com/li-xinyang/OS_FrontendMaster-dl|100|
		|SchoolIdolAPI|https://github.com/MagiCircles/SchoolIdolAPI|111|
		|mbrochh-dotfiles|https://github.com/mbrochh/mbrochh-dotfiles|66|
		|Spark-practice|https://github.com/XD-DENG/Spark-practice|57|
		|attentional_factorization_machine|https://github.com/hexiangnan/attentional_factorization_machine|65|
		|capsule-net-pytorch|https://github.com/cedrickchee/capsule-net-pytorch|64|
#		Then test if the user clicks on the "R" radio button the following url and stats are displayed
#		|linkTextOfUrl|url|startCnt|
#		|maftools|https://github.com/PoisonAlien/maftools|88|
#		|checkpoint|https://github.com/RevolutionAnalytics/checkpoint|85|
#		|ECharts2Shiny|https://github.com/XD-DENG/ECharts2Shiny|65|
		Then test if the user clicks on the "Ruby" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|emoji-for-jekyll|https://github.com/yihangho/emoji-for-jekyll|83|
		|twemoji|https://github.com/jollygoodcode/twemoji|83|
		|amazon-ecs|https://github.com/jugend/amazon-ecs|513|
		|vuejs|https://github.com/ytbryan/vuejs|51|
		|reread|https://github.com/jollygoodcode/reread|72|
		|attache|https://github.com/choonkeat/attache|189|
		|require_reloader|https://github.com/teohm/require_reloader|126|
		|google_visualr|https://github.com/winston/google_visualr|420|
		|naive-bayes|https://github.com/sausheong/naive-bayes|56|
		|awesome_rails_console|https://github.com/ascendbruce/awesome_rails_console|73|
    Then test if the user clicks on the "Rust" radio button nothing is displayed
    Then test if the user clicks on the "Shell" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|		
    |iOSDylibInjectionDemo|https://github.com/depoon/iOSDylibInjectionDemo|50|
		|EPSignature|https://github.com/ipraba/EPSignature|650|
		|nativefier-icons|https://github.com/jiahaog/nativefier-icons|61|
		Then test if the user clicks on the "Swift" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|UITextField-Navigation|https://github.com/T-Pham/UITextField-Navigation|333|
		|JSONCodable|https://github.com/matthewcheok/JSONCodable|596|
		|SPPatternLock|https://github.com/freesuraj/SPPatternLock|147|
		|Fuzi|https://github.com/cezheng/Fuzi|610|
		|EPContactsPicker|https://github.com/ipraba/EPContactsPicker|401|
		|BTNavigationDropdownMenu|https://github.com/PhamBaTho/BTNavigationDropdownMenu|2060|
		|EPShapes|https://github.com/ipraba/EPShapes|353|
		|swift-of-airbnb|https://github.com/yonasstephen/swift-of-airbnb|279|
		|MKNetworkKit-Swift|https://github.com/MugunthKumar/MKNetworkKit-Swift|71|
		|NHRangeSlider|https://github.com/thehung111/NHRangeSlider|96|
		|PySwiftyRegex|https://github.com/cezheng/PySwiftyRegex|212|
		|ListDiff|https://github.com/lxcid/ListDiff|75|
		|CoinPriceBar|https://github.com/T-Pham/CoinPriceBar|160|
		|susi_iOS|https://github.com/fossasia/susi_iOS|406|
		Then test if the user clicks on the "Tex" radio button the following url and stats are displayed
		|linkTextOfUrl|url|startCnt|
		|the-little-go-book|https://github.com/karlseguin/the-little-go-book|758|
		|the-little-mongodb-book|https://github.com/karlseguin/the-little-mongodb-book|1174|
    Then close the browser opened to test Validate all features of repos per programming language body
     
